import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "../context/UserContext";
import Sidebar from "../components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import type { ReactNode } from "react";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <div className="min-h-screen flex text-black bg-white">
            <Sidebar />
            <main
              className="flex-grow transition-all duration-300"
              style={{ marginLeft: "4rem" }}
              id="main-content"
            >
              {children}
            </main>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}